# permissions for end users to view tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: test-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8test
    app.kubernetes.io/part-of: k8test
    app.kubernetes.io/managed-by: kustomize
  name: test-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - tests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - tests/status
  verbs:
  - get
